services:
  docs:
    image: mypet_local_docs
    container_name: mypet_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./mypet:/app/mypet:z
    ports:
      - '9000:9000'
    command: /start-docs
