# Generated by Django 5.0.9 on 2025-03-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
