# Generated by Django 5.0.9 on 2025-01-27 02:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('modified_by', models.UUIDField(editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('modified_by', models.UUIDField(editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.district')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pet')),
                ('point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.point')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
