# Generated by Django 5.0.9 on 2025-03-15 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_contact_number_post_date_post_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.post')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.post',),
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.post')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.post',),
        ),
    ]
