# Generated by Django 5.0.9 on 2025-03-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_point_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='coordinate',
        ),
        migrations.AddField(
            model_name='point',
            name='lat',
            field=models.DecimalField(decimal_places=6, default='0.0', max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='long',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
    ]
