# Generated by Django 5.0.9 on 2025-03-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_point_coordinate_point_lat_point_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
