# Generated by Django 5.0.9 on 2025-04-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_pet_pet_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='has_reward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='reward',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
